### ISSUE TITLE
Navbar overlaps text

### ISSUE THREAD

**Issue by emersoncloud** [CameraKit/camerakit-website#14]
When scrolling down, the CameraKit logos in the Navbar overlap text on the site.

![image](https://user-images.githubusercontent.com/13784188/41474853-161995dc-708b-11e8-99f7-d1cb63cfbb8e.png)

Resolved via changing the Navbar BG to a semi-transparent white once scrolling down. Can be resolved in the refactored codebase by @WhiteRaBot17

**Comment by WhiteRaBot17** [comment]
On it! Thanks
