### ISSUE TITLE
Website is down

### ISSUE THREAD

**Issue by rsyring** [CameraKit/camerakit-website#15]
What I see on the front page:

![image](https://user-images.githubusercontent.com/109467/42396778-1ea4d6ce-8131-11e8-9c72-fcce9881d6a9.png)

**Comment by austinkettner** [comment]
Thanks for letting us know! We have been using Heroku but are going to migrate it this weekend to Google Cloud.

In the meantime we got it back up and running! https://www.camerakit.website

Thanks again for pointing this out, very helpful!
