### ISSUE TITLE
Update Website Design

### ISSUE THREAD

**Issue by austinkettner** [CameraKit/camerakit-website#6]
- [x] Update Website based on Latest Design in Private Slack/Dropbox (Do not include Addons section)
- [x] Include /jpegkit route which redirects to https://github.com/CameraKit/jpegkit-android
- [x] Include Email Subscribe in Website Design
- [ ] Implement Intro on-scroll animation
- [x] Fetch Latest News from https://medium.com/camerakit
- [ ] For Intro Animation, No parallax (white part) for the main page after the device animation tho =P

Include on 'Develop' branch

**Comment by nchan0154** [comment]
Email subscribe form - anything you want me to hook this up to?
Medium news - It seems like medium doesn't make this easy to get via api. I have implemented a hacky solution with corsanywhere, i dont know if this is production-viable

@austinkettner

**Comment by austinkettner** [comment]
Let's hook this up to Mailchimp. Details coming in Slack.

Ok, will test Medium integration. Biggest concern being?

Menu not needed right now, full menu and animation is ready though. Will share in Slack.

**Comment by nchan0154** [comment]
For medium, they simply do not have a get API. I implemented one of the workarounds listed [here](https://stackoverflow.com/questions/36097527/how-to-retrieve-medium-stories-for-a-user-from-the-api).
